{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "@pytest.mark.run(order=4)\n    def test_b():\n        \"\"\"第二条\"\"\"\n        print(\"------------------->test_b\")\n>       assert 0\nE       assert 0\n\nscript\\test_order.py:24: AssertionError"}, "description": "第二条", "start": 1574227812052, "stop": 1574227812052, "uuid": "c5806efd-c89f-48b3-8152-eda24eefbd7a", "historyId": "bb16357249b0a497a724cdf84f616334", "testCaseId": "ca6a7032ab1edd3c395117b226bde1ed", "fullName": "script.test_order#test_b", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_order"}, {"name": "host", "value": "DESKTOP-E0IFP26"}, {"name": "thread", "value": "13012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_order"}]}